---
title: select
editor_options: 
  chunk_output_type: console
---

```{r knitr_config, code=readLines("_knitr_config.R"), echo=FALSE}
```

*********************************************************************

* https://www.w3schools.com/sql/default.asp  
* https://www.w3schools.com/sql/sql_quickref.asp  
* https://docs.telemetry.mozilla.org/concepts/sql_style.html

*********************************************************************

## faqs

* how to use [case when](#case-when)  
* how to use [having](#having)  
* how to do a [grouped sum](#grouped-aggregations)  

*********************************************************************

## structure

```sql
select column_name(s)
from table_name
where condition
group by column_name(s)
having condition
order by column_name(s);
```

*********************************************************************

## basics

```sql
select * from table
```

```sql
select * from table limit 10
```

```sql
select distinct col1, col2 from table
```

*********************************************************************

## clauses

### where {#where}

#### like

* the 'like' predicate is used to search for a string pattern in a column  
* the `%` is a wildcard character and represents 0 or more of any character and can be placed at the start or end of the pattern

```sql
select col1 from table
where col2 like 'asdf%';
```

```sql
select col1 from table
where col2 not like 'asdf%';
```

#### like any

```sql
select * from table
where col like any (
  'this %',
  'that %'
)
```

#### and / or

```sql
select col1 from table
where (col2 = 1 or col2 = 2)
and (col3 = 'A' or col3 = 'B');
```

#### between and

Alternative to `col >= x and col <= y` (i.e. between is inclusive)

```sql
select col1 from table
where col2 between 1 and 2; 
```

#### in 

```sql
select col1 from table
where col2 in (1, 10, 100);
```

#### is

```sql
select col1 from table
where col2 is null;
```

```sql
select col1 from table
where col2 is not null;
```

#### comparison operators

```sql
select col1 from table
where col2 >= x and col2 <= y; 
```

```sql
select col1 from table
where col2 <> x -- not equal to
```

### group by {#group-by}

```sql
select col, count(col) as n
from table
group by col;
```

### having {#having}

The having clause was added to SQL because the where keyword could not be used with aggregate functions.

Works only with `group by`

```sql
select col1 from table
group by col1
having count(col2) > 10;
```

```sql
select col1, count(col1) as n
from table
group by col1
having count(col1) > 10;
```

### order by {#order-by}

in ascending order by default

```sql
select col1 from table
order by col2, col3;
```

in descending order - using keyword `desc`

```sql
select col1 from table
order by col2 desc, col3;
```

by column position rather than name

```sql
select col1 from table
order by 2, 3;
```

*********************************************************************

## built-in functions

### aggregate functions

* `avg`  
* `count`  
* `max`  
* `min`  
* `sum`  

```sql
select count(*) as n_col
from table;
```

```sql
select count(col1) as n_col
from table
where col1='asdf';
```

```sql
select count(distinct col) as n_distinct_col1
from table;
```

```sql
select count(col) * 100.0 / count(*) as asdf
from table;
```

```sql
select 
  avg(col) as avg, 
  max(col) as max, 
  sum(col) as sum
from table;
```

```sql
select 
  avg(col1 / col2) as avg, 
  max(col1 + col2) as max, 
  sum(col1 * col2) as sum
from table;
```

#### filtered aggregations {#filtered-aggregations}

```sql
select 
  avg(col2) as avg, 
  max(col2) as max, 
  sum(col2) as sum
from table
where col1 = val
```

#### grouped aggregations {#grouped-aggregations}

```sql
select 
  col1
  avg(col2) as avg_col1, 
  max(col2) as max_col1, 
  sum(col2) as sum_col1,
from table
group by col1
```

### scalar and string functions

* round  
* length - length of string  
* ucase - convert string to upper case  
* lcase - convert string to lower case  

```sql
select * from table
where lcase(col) = 'hello'
```

```sql
select distinct(ucase(col1)) from table
```

### date and time functions

* year  
* month  
* day  
* dayofweek  
* dayofmonth  
* dayofyear  
* month - converts date to `'01'`, `'02'`, ..., `'12'`  
* hour  
* minute  
* second  

special registers

* current_date  
* current_time  

```sql
select 
  current_date - col1 + 3 days as foo, 
  month(col2) as bar
from table
```

## misc

### case when {#case-when}

```sql
case
    when condition1 then value1
    when condition2 then value2
    ...
    when conditionN then valueN
    else value0
end;
```



